# Generated by Django 3.1.4 on 2020-12-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined',
            new_name='date_joined',
        ),
    ]
