# Generated by Django 3.1.4 on 2020-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201225_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
