# Generated by Django 3.1.4 on 2021-01-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201226_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='shop.shop'),
            preserve_default=False,
        ),
    ]
